name: CI/CD

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Cache Docker layers
        uses: actions/cache@v3.2.4
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ matrix.version }}-${{ github.sha }}
          restore-keys: docker-buildx-${{ matrix.version }}-

      - name: Build
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache/${{ matrix.version }} \
            --cache-to type=local,dest=/tmp/.buildx-cache/${{ matrix.version }} \
            --output type=docker \
            --tag kooldev/node:${{ matrix.version }} \
            ${{ matrix.version }}

      - name: Tests
        run: |
          docker run kooldev/node:${{ matrix.version }} node -v;
          docker run kooldev/node:${{ matrix.version }} npm -v;
          docker run kooldev/node:${{ matrix.version }} yarn -v;

          docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }} node -v;
          docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }} npm -v;
          docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }} yarn -v;

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-node'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-node'
        run: |
          docker push kooldev/node:${{ matrix.version }}
