name: CI/CD

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        type: ['', '-qa']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ matrix.version }}${{ matrix.type }}-${{ github.sha }}
          restore-keys: docker-buildx-${{ matrix.version }}${{ matrix.type }}-

      - name: Build
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache/${{ matrix.version }}${{ matrix.type }} \
            --cache-to type=local,dest=/tmp/.buildx-cache/${{ matrix.version }}${{ matrix.type }} \
            --output type=docker \
            --tag kooldev/node:${{ matrix.version }}${{ matrix.type }} \
            ${{ matrix.version }}${{ matrix.type }}

      - name: Build (adonis)
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache/${{ matrix.version }}-adonis${{ matrix.type }} \
            --cache-to type=local,dest=/tmp/.buildx-cache/${{ matrix.version }}-adonis${{ matrix.type }} \
            --output type=docker \
            --tag kooldev/node:${{ matrix.version }}-adonis${{ matrix.type }} \
            ${{ matrix.version }}-adonis${{ matrix.type }}

      - name: Build (nest)
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache/${{ matrix.version }}-nest${{ matrix.type }} \
            --cache-to type=local,dest=/tmp/.buildx-cache/${{ matrix.version }}-nest${{ matrix.type }} \
            --output type=docker \
            --tag kooldev/node:${{ matrix.version }}-nest${{ matrix.type }} \
            ${{ matrix.version }}-nest${{ matrix.type }}

      - name: Build (latest)
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-node' && matrix.version == '14'
        run: |
          if [ "${{ matrix.type }}" == "-qa" ]; then
            docker tag kooldev/node:${{ matrix.version }}-qa kooldev/node:qa
          else
            docker tag kooldev/node:${{ matrix.version }} kooldev/node:latest
          fi

          docker tag kooldev/node:${{ matrix.version }}-adonis${{ matrix.type }} kooldev/node:adonis${{ matrix.type }}
          docker tag kooldev/node:${{ matrix.version }}-nest${{ matrix.type }} kooldev/node:nest${{ matrix.type }}

      - name: Tests
        run: |
          for suffix in '' -adonis -nest; do
            docker run kooldev/node:${{ matrix.version }}$suffix${{ matrix.type }} node -v;
            docker run kooldev/node:${{ matrix.version }}$suffix${{ matrix.type }} npm -v;
            docker run kooldev/node:${{ matrix.version }}$suffix${{ matrix.type }} yarn -v;

            docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }}$suffix${{ matrix.type }} node -v;
            docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }}$suffix${{ matrix.type }} npm -v;
            docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }}$suffix${{ matrix.type }} yarn -v;
          done

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-node'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-node'
        run: |
          docker push kooldev/node:${{ matrix.version }}${{ matrix.type }}
          docker push kooldev/node:${{ matrix.version }}-adonis${{ matrix.type }}
          docker push kooldev/node:${{ matrix.version }}-nest${{ matrix.type }}

      - name: Push to DockerHub (latest)
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-node' && matrix.version == '14'
        run: |
          if [ "${{ matrix.type }}" == "-qa" ]; then
            docker push kooldev/node:qa
          else
            docker push kooldev/node:latest
          fi

          docker push kooldev/node:adonis${{ matrix.type }}
          docker push kooldev/node:nest${{ matrix.type }}
