name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [12, 14]

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build images
      run: |
        docker build --pull -t kooldev/node:${{ matrix.version }} ${{ matrix.version }}
        docker build -t kooldev/node:${{ matrix.version }}-adonis ${{ matrix.version }}-adonis
        docker build -t kooldev/node:${{ matrix.version }}-adonis-qa ${{ matrix.version }}-adonis-qa
        docker build -t kooldev/node:${{ matrix.version }}-qa ${{ matrix.version }}-qa

    - name: Tag latest images
      if: matrix.version == '14'
      run: |
        docker tag kooldev/node:${{ matrix.version }} kooldev/node:latest
        docker tag kooldev/node:${{ matrix.version }}-adonis kooldev/node:adonis
        docker tag kooldev/node:${{ matrix.version }}-adonis-qa kooldev/node:adonis-qa
        docker tag kooldev/node:${{ matrix.version }}-qa kooldev/node:qa

    - name: Test images
      run: |
        for suffix in '' -adonis -adonis-qa -qa; do
          docker run kooldev/node:${{ matrix.version }}$suffix node -v;
          docker run kooldev/node:${{ matrix.version }}$suffix npm -v;
          docker run kooldev/node:${{ matrix.version }}$suffix yarn -v;

          docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }}$suffix node -v;
          docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }}$suffix npm -v;
          docker run -e ASUSER=1000 kooldev/node:${{ matrix.version }}$suffix yarn -v;
        done

    - name: Push to hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        docker push kooldev/node:${{ matrix.version }}
        docker push kooldev/node:${{ matrix.version }}-adonis
        docker push kooldev/node:${{ matrix.version }}-adonis-qa
        docker push kooldev/node:${{ matrix.version }}-qa

    - name: Push to hub latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.version == '14'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        docker push kooldev/node:latest
        docker push kooldev/node:adonis
        docker push kooldev/node:adonis-qa
        docker push kooldev/node:qa
